name: go

include:
  - infra/docker-compose.infra.yml
  - monitoring/docker-compose.monitoring.yml
  - tls/docker-compose.tls.yml

services:
  auth:
    build:
      context: ..
      dockerfile: services/auth/Dockerfile
    container_name: auth
    environment:
      - AUTH_PORT=8081
      - AUTH_GRPC_PORT=50051
    ports:
      - "8081:8081"  # HTTP
      - "50051:50051"  # gRPC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - app-network

  graphql:
    build:
      context: ..
      dockerfile: services/graphql/Dockerfile
    container_name: graphql
    environment:
      - GRAPHQL_PORT=8090
      - AUTH_GRPC_ADDR=auth:50051
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=tasks_user
      - DB_PASSWORD=tasks_pass
      - DB_NAME=tasks_db
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
      auth:
        condition: service_healthy
    networks:
      - app-network

  tasks:
    build:
      context: ..
      dockerfile: services/tasks/Dockerfile
    container_name: tasks
    environment:
      - TASKS_PORT=8082
      - AUTH_GRPC_ADDR=auth:50051
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=tasks_user
      - DB_PASSWORD=tasks_pass
      - DB_NAME=tasks_db
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - CACHE_TTL_SECONDS=120
      - CACHE_TTL_JITTER_SECONDS=30
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - JOB_QUEUE=task_jobs
    ports:
      - "8082:8082"  # HTTP (/tasks)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth:
        condition: service_healthy

  worker:
    build:
      context: ..
      dockerfile: services/worker/Dockerfile
    container_name: worker
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - JOB_QUEUE=task_jobs
      - DLQ_QUEUE=task_jobs_dlq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

